[supervisord]
nodaemon=true

[program:exceptionless]
command=dotnet Exceptionless.Web.dll
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
