[supervisord]
nodaemon=true

[program:exceptionless]
command=/usr/share/elasticsearch/.dotnet/dotnet Exceptionless.Web.dll
environment=PATH="/usr/share/elasticsearch/.dotnet:%(ENV_PATH)s",DOTNET_ROOT="/usr/share/elasticsearch/.dotnet"
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
